/**
 * Robots directive checks.
 *
 * Two independent mechanisms decide whether a URL is crawled and whether it is
 * indexed, and the failure mode this file is mostly about is the two of them
 * disagreeing. A disallowed URL is never fetched, so a noindex inside it is never
 * read - the pair cancels, and the URL can stay in the index indefinitely.
 */
import {
  pageCheck, gate, findingsFor, location, ev, robotsGroups, robotsDirectives,
  declaresNoindex, pathOf, finding,
} from '../check-support.ts';

/** Route modules that generate robots.txt at build or request time. */
const ROBOTS_GENERATORS = [
  /(^|\/)app\/robots\.(ts|tsx|js|mjs|cjs)$/,
  /(^|\/)src\/app\/robots\.(ts|tsx|js|mjs|cjs)$/,
  /(^|\/)pages\/robots\.txt\.(ts|tsx|js|jsx|mjs)$/,
  /(^|\/)routes\/robots\.txt(\/|\.)/,
  /(^|\/)robots\.route\.(ts|js|mjs)$/,
  /(^|\/)robots\.(ts|js|mjs)\.config\./,
];

const HTML_MARKUP = /<!doctype\s+html|<html[\s>]|<script[\s>]|<div[\s>]/i;

/**
 * Compile a robots path value into a matcher.
 *
 * This implements the matching behaviour Google documents: the value is a path
 * prefix, `*` matches any run of characters, and a trailing `$` anchors the end of
 * the URL. Other crawlers implement subsets of this - Bing historically ignored
 * `$`, and some ignore `*` - which is exactly why the checks below report a
 * *conflict between two directives* rather than asserting what any particular
 * crawler will do with the URL.
 */
function ruleMatcher(value) {
  let body = String(value ?? '');
  const anchored = body.endsWith('$');
  if (anchored) body = body.slice(0, -1);
  const source = [...body]
    .map((ch) => (ch === '*' ? '.*' : ch.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')))
    .join('');
  return new RegExp(`^${source}${anchored ? '$' : ''}`);
}

/**
 * Which directive wins for a path, per the documented longest-match rule.
 *
 * Returns `{ decision, rule }` where decision is 'allow', 'disallow', or null when
 * no rule in the group matches. An empty `Disallow:` value is the documented way
 * to say "nothing is disallowed", so it never matches.
 */
export function decideForPath(group, path) {
  let best = null;
  for (const rule of group.rules) {
    if (rule.field === 'crawl-delay') continue;
    if (rule.field === 'disallow' && rule.value === '') continue;
    if (!rule.value) continue;
    if (!ruleMatcher(rule.value).test(path)) continue;
    const length = rule.value.replace(/\$$/, '').length;
    // Longest match wins; on an equal-length tie the documented behaviour is that
    // the less restrictive directive wins, so Allow beats Disallow.
    if (!best || length > best.length || (length === best.length && rule.field === 'allow')) {
      best = { length, rule };
    }
  }
  if (!best) return { decision: null, rule: null };
  return { decision: best.rule.field === 'allow' ? 'allow' : 'disallow', rule: best.rule };
}

/** The group a wildcard crawler would follow, or null when none names `*`. */
function wildcardGroup(text) {
  const { groups } = robotsGroups(text);
  const matching = groups.filter((g) => g.agents.some((a) => a.trim() === '*'));
  if (!matching.length) return null;
  // Real crawlers merge same-agent groups. robots-group-contradiction reports the
  // duplication separately; here the merge is performed so the decision reflects
  // what a crawler would actually do.
  return { agents: ['*'], rules: matching.flatMap((g) => g.rules), line: matching[0].line };
}

const robotsTxtPresent = {
  id: 'robots-txt-present',
  requirements: ['SEO-081'],
  level: 'SOURCE',
  title: 'A valid robots.txt exists at the host root',
  run(snapshot) {
    const resource = snapshot.robots_txt;
    const generators = ROBOTS_GENERATORS.flatMap((pattern) => snapshot.findAll(pattern));

    if (!resource) {
      if (generators.length || snapshot.profile?.facts?.has_robots_txt?.value === true) {
        // A route module means the bytes exist only once something serves them,
        // and the bytes are the whole subject of this requirement.
        return {
          status: 'NEEDS_RUNTIME',
          findings: [],
          detail: `robots.txt is generated by ${generators[0] || 'a route module'}; fetch /robots.txt from a served origin to verify it`,
        };
      }
      return {
        status: 'FAIL',
        findings: [finding({
          requirement_id: 'SEO-081',
          check_id: robotsTxtPresent.id,
          location: 'robots.txt',
          severity: 'HIGH',
          detail: 'no robots.txt file and no route module that generates one',
          evidence: [
            ev('ROBOTS_TXT', { observed: 'absent' }),
            ev('HTTP_STATUS', { expected: 200, note: 'not verified; no served origin was available' }),
          ],
        })],
      };
    }

    const out = [];
    const text = resource.text;
    if (HTML_MARKUP.test(text)) {
      out.push({
        requirement_id: 'SEO-081',
        location: resource.path,
        severity: 'HIGH',
        detail: 'robots.txt contains HTML markup, which is the signature of an application fallback being served in place of the file',
        evidence: [
          ev('ROBOTS_TXT', { path: resource.path, observed: text.slice(0, 200) }),
          ev('HTTP_HEADER', { expected: 'content-type: text/plain', note: 'not verified from source alone' }),
        ],
      });
    } else if (!/^\s*user-agent\s*:/im.test(text)) {
      out.push({
        requirement_id: 'SEO-081',
        location: resource.path,
        severity: 'HIGH',
        detail: 'robots.txt declares no User-agent line, so none of its rules belong to any crawler',
        evidence: [
          ev('ROBOTS_TXT', { path: resource.path, observed: text.slice(0, 200) }),
          ev('HTTP_STATUS', { observed: null, note: 'file present in the repository' }),
        ],
      });
    }
    return { status: out.length ? 'FAIL' : 'PASS', findings: out.map((i) => finding({ check_id: robotsTxtPresent.id, ...i })) };
  },
};

const robotsSitemapReference = {
  id: 'robots-sitemap-reference',
  requirements: ['SEO-082'],
  level: 'SOURCE',
  title: 'robots.txt declares an absolute sitemap URL',
  run(snapshot) {
    const resource = snapshot.robots_txt;
    if (!resource) return { status: 'NOT_APPLICABLE', findings: [], detail: 'no robots.txt to inspect' };

    const declared = robotsGroups(resource.text).other.filter((e) => e.field === 'sitemap');
    const hasSitemap = snapshot.sitemaps.length > 0 || snapshot.profile?.facts?.has_sitemap?.value === true;
    const out = [];

    if (!declared.length) {
      if (!hasSitemap) {
        return { status: 'NOT_APPLICABLE', findings: [], detail: 'project has no sitemap to declare' };
      }
      out.push({
        requirement_id: 'SEO-082',
        location: resource.path,
        severity: 'MEDIUM',
        detail: 'the project ships a sitemap but robots.txt does not point at it, so discovery depends entirely on the crawler guessing the path',
        evidence: [
          ev('ROBOTS_TXT', { path: resource.path, observed: 'no Sitemap: directive' }),
          ev('SITEMAP', { available: snapshot.sitemaps.map((s) => s.path) }),
        ],
      });
    }

    for (const entry of declared) {
      if (/^https?:\/\/\S+$/i.test(entry.value)) continue;
      out.push({
        requirement_id: 'SEO-082',
        location: `${resource.path}:${entry.line}`,
        severity: 'MEDIUM',
        detail: `Sitemap value "${entry.value}" is not an absolute URL; the sitemap protocol requires one because robots.txt is fetched without page context`,
        evidence: [
          ev('ROBOTS_TXT', { path: resource.path, line: entry.line, observed: entry.raw }),
          ev('SITEMAP', { declared: entry.value }),
        ],
      });
    }
    return { status: out.length ? 'FAIL' : 'PASS', findings: out.map((i) => finding({ check_id: robotsSitemapReference.id, ...i })) };
  },
};

const KNOWN_FIELDS = new Set(['user-agent', 'allow', 'disallow', 'sitemap', 'crawl-delay', 'host', 'clean-param', 'noindex', 'request-rate', 'visit-time']);

const robotsGroupContradiction = {
  id: 'robots-group-contradiction',
  requirements: ['SEO-083'],
  level: 'SOURCE',
  title: 'robots.txt groups contain no self-contradicting rules',
  run(snapshot) {
    const resource = snapshot.robots_txt;
    if (!resource) return { status: 'NOT_APPLICABLE', findings: [], detail: 'no robots.txt to inspect' };

    const { groups, preamble, other } = robotsGroups(resource.text);
    const at = (line) => `${resource.path}:${line}`;
    const out = [];
    const evidenceAt = (line, observed, note) => [
      ev('ROBOTS_TXT', { path: resource.path, line, observed }),
      ev('VALIDATOR_OUTPUT', { rule: 'robots-group-contradiction', note }),
    ];

    for (const entry of preamble) {
      out.push({
        requirement_id: 'SEO-083',
        location: at(entry.line),
        severity: 'HIGH',
        detail: `"${entry.raw}" appears before any User-agent line, so it belongs to no group and is ignored`,
        evidence: evidenceAt(entry.line, entry.raw, 'rule outside any user-agent group'),
      });
    }

    // A user-agent named in two groups is merged by real crawlers, so the effective
    // rule set is the union rather than either block as written.
    const seenAgents = new Map();
    for (const group of groups) {
      for (const agent of group.agents) {
        const key = agent.trim().toLowerCase();
        if (seenAgents.has(key)) {
          out.push({
            requirement_id: 'SEO-083',
            location: at(group.line),
            severity: 'HIGH',
            detail: `user-agent "${agent}" is also declared at line ${seenAgents.get(key)}; crawlers merge the groups, so the effective policy is the union of both and not the block as written`,
            evidence: evidenceAt(group.line, `User-agent: ${agent}`, `duplicate group; first at line ${seenAgents.get(key)}`),
          });
        } else {
          seenAgents.set(key, group.line);
        }
      }
    }

    for (const group of groups) {
      const byValue = new Map();
      for (const rule of group.rules) {
        if (rule.field === 'crawl-delay') continue;
        const key = `${rule.value}`;
        if (!byValue.has(key)) byValue.set(key, []);
        byValue.get(key).push(rule);
      }
      for (const [value, rules] of byValue) {
        const fields = new Set(rules.map((r) => r.field));
        if (fields.size > 1) {
          out.push({
            requirement_id: 'SEO-083',
            location: at(rules[rules.length - 1].line),
            severity: 'HIGH',
            detail: `Allow and Disallow both name the path "${value}" in the group for ${group.agents.join(', ')}; the tie resolves to Allow, which is probably not what the Disallow was for`,
            evidence: evidenceAt(rules[rules.length - 1].line, rules.map((r) => r.raw), 'allow/disallow on an identical path'),
          });
        }
      }

      const blanket = group.rules.find((r) => r.field === 'disallow' && (r.value === '/' || r.value === '/*'));
      const allows = group.rules.filter((r) => r.field === 'allow' && r.value);
      if (blanket && allows.length) {
        out.push({
          requirement_id: 'SEO-083',
          location: at(blanket.line),
          severity: 'HIGH',
          detail: `the group for ${group.agents.join(', ')} disallows everything and then allows ${allows.length} path(s); the result depends on longest-match arbitration rather than on the order written, so the intent needs to be stated explicitly`,
          evidence: evidenceAt(blanket.line, [blanket.raw, ...allows.map((a) => a.raw)], 'blanket disallow with exceptions'),
        });
      }
    }

    for (const entry of other) {
      if (KNOWN_FIELDS.has(entry.field)) continue;
      out.push({
        requirement_id: 'SEO-083',
        location: at(entry.line),
        severity: 'HIGH',
        detail: `"${entry.field}" is not a robots.txt directive; unrecognised lines are skipped silently, so whatever it was meant to do is not happening`,
        evidence: evidenceAt(entry.line, entry.raw, 'unknown directive field'),
      });
    }

    return findingsFor(robotsGroupContradiction, out);
  },
};

const robotsMetaNoindexUnintended = {
  id: 'robots-meta-noindex-unintended',
  requirements: ['SEO-084'],
  level: 'RUNTIME',
  title: 'noindex appears only where exclusion is intended',
  run(snapshot) {
    return pageCheck(robotsMetaNoindexUnintended, snapshot, (page) => {
      const directives = robotsDirectives(page);
      if (!directives.length) return [];
      const noindexing = directives.filter((d) => /(^|[\s,])(noindex|none)([\s,]|$)/i.test(d.value));
      const out = [];

      // The capture asserts the page is meant to be indexable. If the bytes say
      // otherwise, one of the two is wrong and a human has to decide which.
      if (noindexing.length && page.indexable !== false) {
        out.push({
          requirement_id: 'SEO-084',
          location: location(page, noindexing[0].index),
          severity: 'CRITICAL',
          detail: `${noindexing[0].source} serves "${noindexing[0].value}" on a page recorded as indexable; if that directive is wrong the page is being removed from the index, and if the record is wrong the capture is misleading`,
          evidence: [
            ev('RENDERED_HTML', { url: page.url, observed: noindexing.map((d) => `${d.source}: ${d.value}`) }),
            ev('HTTP_HEADER', { url: page.url, 'x-robots-tag': page.headers?.['x-robots-tag'] ?? null }),
            ev('ROUTE', { url: page.url, recorded_indexable: page.indexable !== false }),
          ],
        });
      }

      // A meta tag and a header that disagree is unresolvable from the outside:
      // the most restrictive interpretation is what applies, so the permissive
      // half is dead configuration someone is relying on.
      const metaSays = directives.some((d) => d.source !== 'X-Robots-Tag' && /(^|[\s,])(noindex|none)([\s,]|$)/i.test(d.value));
      const headerPresent = directives.some((d) => d.source === 'X-Robots-Tag');
      const headerSays = directives.some((d) => d.source === 'X-Robots-Tag' && /(^|[\s,])(noindex|none)([\s,]|$)/i.test(d.value));
      if (headerPresent && metaSays !== headerSays) {
        out.push({
          requirement_id: 'SEO-084',
          location: location(page),
          severity: 'CRITICAL',
          detail: `meta robots and X-Robots-Tag disagree about noindex on this page (meta says ${metaSays ? 'noindex' : 'index'}, header says ${headerSays ? 'noindex' : 'index'}); the restrictive one wins and the other is dead configuration`,
          evidence: [
            ev('RENDERED_HTML', { url: page.url, observed: directives.filter((d) => d.source !== 'X-Robots-Tag').map((d) => d.value) }),
            ev('HTTP_HEADER', { url: page.url, 'x-robots-tag': page.headers?.['x-robots-tag'] ?? null }),
            ev('ROUTE', { url: page.url }),
          ],
        });
      }
      return out;
    });
  },
};

const crawlIndexDirectiveConflict = {
  id: 'crawl-index-directive-conflict',
  requirements: ['SEO-094'],
  level: 'RUNTIME',
  title: 'Crawl directives and index directives do not cancel each other',
  run(snapshot) {
    const resource = snapshot.robots_txt;
    if (!resource) return { status: 'NOT_APPLICABLE', findings: [], detail: 'no robots.txt to compare against' };
    const blocked = gate(snapshot);
    if (blocked) return blocked;

    const group = wildcardGroup(resource.text);
    if (!group) {
      return { status: 'NOT_APPLICABLE', findings: [], detail: 'robots.txt declares no group for *' };
    }

    const items = [];
    for (const page of snapshot.pages) {
      if (!declaresNoindex(page)) continue;
      const path = pathOf(page.url) ?? page.url;
      const { decision, rule } = decideForPath(group, path);
      if (decision !== 'disallow') continue;
      items.push({
        requirement_id: 'SEO-094',
        location: location(page),
        severity: 'HIGH',
        detail: `${path} is disallowed by "${rule.raw}" (robots.txt line ${rule.line}) and also serves a noindex directive; a crawler that obeys the disallow never fetches the page and so never reads the noindex, which is how a URL stays indexed while both directives look correct`,
        evidence: [
          ev('ROBOTS_TXT', { path: resource.path, line: rule.line, observed: rule.raw }),
          ev('RENDERED_HTML', { url: page.url, observed: robotsDirectives(page).map((d) => `${d.source}: ${d.value}`) }),
          ev('HTTP_HEADER', { url: page.url, 'x-robots-tag': page.headers?.['x-robots-tag'] ?? null }),
        ],
      });
    }
    return findingsFor(crawlIndexDirectiveConflict, items);
  },
};

/* ------------------------------------------------------- AI crawler policy */

/**
 * Automated clients, classified by the purpose their operator documents for them.
 *
 * The classification is the whole point. "Block the AI bots" is not an
 * instruction any file can carry out, because the operators do not send one
 * token for one job: OpenAI documents separate training, search, and
 * user-requested crawlers, and blocking the training token says nothing about
 * the other two. A policy written against "AI" therefore blocks retrieval
 * whenever it blocks training, which is the commonest way a site removes itself
 * from AI answers by accident.
 *
 * Two facts here are not obvious and both change what a correct file looks like:
 *
 *   - `PRODUCT_CONTROL` tokens have no HTTP user-agent at all. Google states that
 *     Google-Extended is not a separate crawler identity but an opt-out applied to
 *     data collected by the user agents already visiting the site. Writing
 *     `User-agent: Google-Extended` therefore matches no request, and treating it
 *     as evidence of a training block would be reading a directive that cannot
 *     fire.
 *   - `USER_TRIGGERED` clients are requested by a person reading a page they can
 *     already open, so refusing them is an access-control decision rather than a
 *     discoverability one, and robots.txt is not the place to make it.
 *
 * Every token here is one an operator documents on its own site, and each is cited
 * on SEO-291. That is a deliberate limit, not an oversight: a token whose operator
 * publishes nothing cannot be classified from evidence, and a table padded with
 * community-compiled lists is exactly the unverified assertion this package exists
 * to keep out. Tokens published without first-party documentation are therefore
 * absent, and an absent token is never reported - a file may name twenty crawlers
 * this check has heard of none.
 *
 * Tokens are matched case-insensitively, which is what every operator's parser
 * does.
 */
const AI_CLIENTS = [
  // Search / AI-answer discovery. Blocking one of these is the mistake this check
  // exists to name.
  { token: 'OAI-SearchBot', operator: 'OpenAI', purpose: 'search' },
  { token: 'Claude-SearchBot', operator: 'Anthropic', purpose: 'search' },
  { token: 'PerplexityBot', operator: 'Perplexity', purpose: 'search' },
  // User-triggered fetches, requested on behalf of a reader.
  { token: 'ChatGPT-User', operator: 'OpenAI', purpose: 'user_action' },
  { token: 'Claude-User', operator: 'Anthropic', purpose: 'user_action' },
  { token: 'Perplexity-User', operator: 'Perplexity', purpose: 'user_action' },
  { token: 'Google-CloudVertexBot', operator: 'Google', purpose: 'user_action' },
  { token: 'meta-externalfetcher', operator: 'Meta', purpose: 'user_action' },
  // Training / dataset collection. Declining this is a legitimate policy choice.
  { token: 'GPTBot', operator: 'OpenAI', purpose: 'training' },
  { token: 'ClaudeBot', operator: 'Anthropic', purpose: 'training' },
  { token: 'CCBot', operator: 'Common Crawl', purpose: 'training' },
  { token: 'meta-externalagent', operator: 'Meta', purpose: 'training' },
  // Product controls. No HTTP user-agent; the directive matches no request.
  { token: 'Google-Extended', operator: 'Google', purpose: 'product_control' },
  { token: 'Applebot-Extended', operator: 'Apple', purpose: 'product_control' },
];

/** Purpose labels, spelled out once so a finding reads as prose. */
const PURPOSE_LABEL = {
  search: 'search and AI-answer discovery',
  user_action: 'user-triggered fetching',
  training: 'training or dataset collection',
  product_control: 'a product-level control with no HTTP user-agent',
};

/**
 * Every group in the file, merged per agent the way a crawler merges them, so a
 * token named in two groups gets one decision.
 */
function groupsByAgent(text) {
  const merged = new Map();
  for (const group of robotsGroups(text).groups) {
    for (const raw of group.agents) {
      const agent = raw.trim().toLowerCase();
      if (!merged.has(agent)) merged.set(agent, []);
      merged.get(agent).push(group);
    }
  }
  return merged;
}

/**
 * Whether a named agent ends up disallowed at the site root.
 *
 * The root path is the only one that answers "is this client allowed on this site
 * at all"; a narrower block such as `Disallow: /private` is a path-level decision
 * and says nothing about discoverability of the public pages.
 */
function blockedAtRoot(text, agent) {
  const groups = groupsByAgent(text).get(agent);
  if (!groups) return false;
  const rules = groups.flatMap((g) => g.rules);
  return decideForPath({ rules }, '/').decision === 'disallow';
}

const aiCrawlerPolicyPurposeSeparated = {
  id: 'ai-crawler-policy-purpose-separated',
  requirements: ['SEO-291', 'SEO-642'],
  level: 'SOURCE',
  title: 'No crawler that feeds AI answers is blocked while training crawlers are allowed',
  run(snapshot) {
    const resource = snapshot.robots_txt;
    if (!resource || !resource.text) {
      return { status: 'NOT_APPLICABLE', findings: [], detail: 'no robots.txt in this project' };
    }
    const text = resource.text;
    const wildcard = wildcardGroup(text);
    const blockedAtRootByWildcard = wildcard ? decideForPath(wildcard, '/').decision === 'disallow' : false;

    const named = new Map(
      AI_CLIENTS.filter((client) => blockedAtRoot(text, client.token.toLowerCase()))
        .map((client) => [client.purpose, client]),
    );

    const findings = [];

    // The specific mistake: retrieval is refused and training is permitted. The
    // site has chosen to be in models and out of answers, which is rarely what
    // either decision was aiming at.
    if (named.has('search') && !named.has('training')) {
      const client = named.get('search');
      findings.push(finding({
        requirement_id: 'SEO-291',
        check_id: 'ai-crawler-policy-purpose-separated',
        location: resource.path,
        severity: 'HIGH',
        detail: `robots.txt blocks ${client.token} (${PURPOSE_LABEL.search}) at the site root while allowing every training crawler, so the site is excluded from ${client.operator} answers and admitted to model training; the two are separate policies and are usually not both intended`,
        evidence: [ev('ROBOTS_TXT', { path: resource.path, blocked: [...named.values()].map((c) => c.token), allowed_training: true })],
      }));
    }

    // The other half of the same mistake: a blanket block. `User-agent: *` with a
    // root disallow takes the search crawlers with it, including the ones the
    // operator's own organic results depend on.
    if (blockedAtRootByWildcard && !named.size) {
      findings.push(finding({
        requirement_id: 'SEO-291',
        check_id: 'ai-crawler-policy-purpose-separated',
        location: resource.path,
        severity: 'HIGH',
        detail: 'robots.txt disallows the site root to every crawler (`User-agent: *`), which removes the pages from AI answers and from ordinary search results alike; declining AI training is done with the documented training tokens, not with a blanket block',
        evidence: [ev('ROBOTS_TXT', { path: resource.path, wildcard_block: true, named_ai_tokens: 0 })],
      }));
    }

    // A product-control token cannot be enforced by a robots.txt group at all, so
    // a file that relies on one records a decision it does not make.
    for (const client of AI_CLIENTS) {
      if (client.purpose !== 'product_control') continue;
      const agent = client.token.toLowerCase();
      if (!groupsByAgent(text).has(agent)) continue;
      if (!/^(?:https?:\/\/)?[^/]/i.test(agent)) continue;
      findings.push(finding({
        requirement_id: 'SEO-642',
        check_id: 'ai-crawler-policy-purpose-separated',
        location: resource.path,
        severity: 'MEDIUM',
        detail: `robots.txt declares a group for ${client.token}, which ${client.operator} documents as a product-level control rather than a crawler identity; the group matches no request, so the file records an intent the wire never enforces`,
        evidence: [ev('ROBOTS_TXT', { path: resource.path, token: client.token, purpose: client.purpose })],
      }));
    }

    return findingsFor(aiCrawlerPolicyPurposeSeparated, findings);
  },
};

export default [
  robotsTxtPresent,
  robotsSitemapReference,
  robotsGroupContradiction,
  robotsMetaNoindexUnintended,
  crawlIndexDirectiveConflict,
  aiCrawlerPolicyPurposeSeparated,
];
